const STRINGS = {
  LABEL_FIRST_NAME: 'First Name *',
  LABEL_LAST_NAME: 'Last Name *',
  LABEL_EMAIL: 'Email *',
  BUTTON_SAVE: 'SAVE',
  LABEL_LICENSE_NUMBER: 'License Number *',
  EMPTY_LICENSE_NUMBER: 'License Number is required',
  LABEL_LICENSE_EXPIRY_DATE: 'License Expiry Date',
  LABEL_LICENSE_CLASS: 'License Class *',
  EMPTY_LICENSE_CLASS: 'License Class is required',
  LABEL_COUNTRY_OF_ISSUE: 'Country Of Issue',
  LABEL_LICENSE_EXPIRY_REMINDER: 'License Expiry Reminder',
  LABEL_DAYS_BEFORE_EXPIRY: 'Days Before Expiry *',
  EMPTY_DAYS_BEFORE_EXPIRY: 'Days Before Expiry is required',
  LABEL_REMINDER_RECIPIENTS: 'Reminder recipients *',
  EMPTY_REMINDER_RECIPIENTS: 'Reminder recipients is required',
  LABEL_LICENSE_IMAGE: 'License Image',
  LABEL_FRONT_PHOTO: 'Front Photo',
  LABEL_BACK_PHOTO: 'Back Photo',
  PLEASE_WAIT: 'Please wait',
  SOMETHING_WENT_WRONG: 'Oops! Something went wrong.',
  EMPTY_FIRST_NAME: 'First name is required',
  EMPTY_LAST_NAME: 'Last name is required',
  CHANGE_PASSWORD: 'Change Password',
  BUTTON_UPDATE: 'UPDATE',
  BUTTON_CANCEL: 'CANCEL',
  LABEL_CURRENT_PASSWORD: 'Current Password',
  LABEL_NEW_PASSWORD: 'New Password',
  LABEL_CONFIRM_NEW_PASSWORD: 'Confirm New Password',
  CURRENT_PASSWORD_EMPTY: 'Please enter your current password',
  NEW_PASSWORD_EMPTY: 'Please enter your new password',
  CONFIRM_PASSWORD_EMPTY: 'Please re-enter your new passsword',
  NEW_PASSWORD_ERROR: 'Atleast 6 char, One capital, One number',
  CONFIRM_PASSWORD_ERROR: "Password doesn't match",
  CHANGE_PASSWORD_SUCCESS:
    'Your password has been reset. Please login again to continue',
  CHANGE: 'Change',
  LABEL_CHANGE_EMAIL: 'Change Email',
  LABEL_NEW_EMAIL: 'New Email',
  LABEL_CONFIRM_NEW_EMAIL: 'Confirm New Email',
  NEW_EMAIL_EMPTY: 'Please enter your new email',
  NEW_EMAIL_ERROR: 'Please enter a valid email',
  CONFIRM_EMAIL_EMPTY: 'Please re-enter your new email',
  CONFIRM_EMAIL_ERROR: "Email doesn't match",
  TITLE_GENERAL: 'General Details',
  TITLE_LICENSE_DETAIL: 'License Details',
  COUNTRY_INDIA: 'India',
  COUNTRY_AUSTRALIA: 'Australia',
  ACKNOWLEDGEMENT_MESSAGE:
    'I accept that all the above-mentioned details are correct',
}

export default STRINGS
