const STRINGS = {
  LABEL_SELECT_VEHICLE: 'Select Vehicle for Booking',
  LISTITEM_ODO_HEADING: 'Odometer',
  LISTITEM_BUTTON_SELECT: 'SELECT',
  LISTITEM_BUTTON_SELECTED: 'SELECTED',
  LABEL_SELECT_FILTERS: 'Select Filters',
  LABEL_VEHICLE_TYPE: 'Vehicle Type',
  LABEL_PRICE_RANGE: 'Price Range',
  LABEL_PRICE_PER_HOUR: 'Price Per Hour',
  LABEL_PRICE_PER_KM: 'Price Per KM',
  LABEL_SEATER: 'Seater',
  LABEL_ATTRIBUTES: 'Attributes',
  NO_VEHICLES_FOUND_1:
    'Sorry! There are no vehicles available as per searched date and time.',
  LISTITEM_SHOW_DETAILS: 'Show Details',
  LISTITEM_HIDE_DETAILS: 'Hide Details',
  DRIVER: 'Driver',
  EMAIL: 'Email',
  REGISTRATION_NUMBER: 'Registration No.',
  VIN: 'VIN',
  BRANCH: 'Branch',
  SEATER: 'Seater',
  FUEL: 'Fuel',
  DOORS: 'Doors',
  LICENSE: 'License',
  COLOR: 'Color',
  BUTTON_NEXT: 'NEXT',
  LABEL_EDIT_BOOKING: 'Edit Booking',
  LABEL_COST_CENTRE: 'Cost Centre',
  SORT_ODO_ASC: 'By Odometer Ascending',
  SORT_ODO_DESC: 'By Odometer Descending',
  SORT_NAME_ASC: 'By Name: A - Z',
  SORT_NAME_DESC: 'By Name: Z - A',
  PLACEHOLDER_SORT_BY: 'Sort Vehicles By',
  MAKE: 'Make',
  MODEL: 'Model',
  BODY_TYPE: 'Body Type',
  YEAR: 'Year',
}

export default STRINGS
