export const BOOKING_EVENTS = {
  LOAD_BOOKING_LIST_START: 'LOAD_BOOKING_LIST_START',
  LOAD_BOOKING_LIST_SUCCESS: 'LOAD_BOOKING_LIST_SUCCESS',
  LOAD_BOOKING_LIST_FAILURE: 'LOAD_BOOKING_LIST_FAILURE',

  LOAD_BOOKING_START: 'LOAD_BOOKING_START',
  LOAD_BOOKING_SUCCESS: 'LOAD_BOOKING_SUCCESS',
  LOAD_BOOKING_FAILURE: 'LOAD_BOOKING_FAILURE',

  LOAD_VEHICLE_START: 'LOAD_VEHICLE_START',
  LOAD_VEHICLE_SUCCESS: 'LOAD_VEHICLE_SUCCESS',
  LOAD_VEHICLE_FAILURE: 'LOAD_VEHICLE_FAILURE',

  LOAD_VEHICLE_FILTERS_START: 'LOAD_VEHICLE_FILTERS_START',
  LOAD_VEHICLE_FILTERS_SUCCESS: 'LOAD_VEHICLE_FILTERS_SUCCESS',
  LOAD_VEHICLE_FILTERS_FAILURE: 'LOAD_VEHICLE_FILTERS_FAILURE',

  LOAD_BOOKING_PURPOSE_START: 'LOAD_BOOKING_PURPOSE_START',
  LOAD_BOOKING_PURPOSE_SUCCESS: 'LOAD_BOOKING_PURPOSE_SUCCESS',
  LOAD_BOOKING_PURPOSE_FAILURE: 'LOAD_BOOKING_PURPOSE_FAILURE',

  CREATE_BOOKING_START: 'CREATE_BOOKING_START',
  CREATE_BOOKING_SUCCESS: 'CREATE_BOOKING_SUCCESS',
  CREATE_BOOKING_FAILURE: 'CREATE_BOOKING_FAILURE',

  LOAD_BOOKING_EDIT_THRESHOLD_START: 'LOAD_BOOKING_EDIT_THRESHOLD_START',
  LOAD_BOOKING_EDIT_THRESHOLD_SUCCESS: 'LOAD_BOOKING_EDIT_THRESHOLD_SUCCESS',
  LOAD_BOOKING_EDIT_THRESHOLD_FAILURE: 'LOAD_BOOKING_EDIT_THRESHOLD_FAILURE',

  CHECK_OUT_START: 'CHECK_OUT_START',
  CHECK_OUT_SUCCESS: 'CHECK_OUT_SUCCESS',
  CHECK_OUT_FAILURE: 'CHECK_OUT_FAILURE',

  CHECK_IN_START: 'CHECK_IN_START',
  CHECK_IN_SUCCESS: 'CHECK_IN_SUCCESS',
  CHECK_IN_FAILURE: 'CHECK_IN_FAILURE',

  LOG_INCIDENT_START: 'LOG_INCIDENT_START',
  LOG_INCIDENT_SUCCESS: 'LOG_INCIDENT_SUCCESS',
  LOG_INCIDENT_FAILURE: 'LOG_INCIDENT_FAILURE',

  LOAD_INCIDENTS_START: 'LOAD_INCIDENTS_START',
  LOAD_INCIDENTS_SUCCESS: 'LOAD_INCIDENTS_SUCCESS',
  LOAD_INCIDENTS_FAILURE: 'LOAD_INCIDENTS_FAILURE',

  LOAD_BOOKING_TRIP_START: 'LOAD_BOOKING_TRIP_START',
  LOAD_BOOKING_TRIP_SUCCESS: 'LOAD_BOOKING_TRIP_SUCCESS',
  LOAD_BOOKING_TRIP_FAILURE: 'LOAD_BOOKING_TRIP_FAILURE',

  DELETE_BOOKING_START: 'DELETE_BOOKING_START',
  DELETE_BOOKING_SUCCESS: 'DELETE_BOOKING_SUCCESS',
  DELETE_BOOKING_FAILURE: 'DELETE_BOOKING_FAILURE',

  LOAD_BOOKING_FILTERS_START: 'LOAD_BOOKING_FILTERS_START',
  LOAD_BOOKING_FILTERS_SUCCESS: 'LOAD_BOOKING_FILTERS_SUCCESS',
  LOAD_BOOKING_FILTERS_FAILURE: 'LOAD_BOOKING_FILTERS_FAILURE',

  CANCEL_BOOKING_START: 'CANCEL_BOOKING_START',
  CANCEL_BOOKING_SUCCESS: 'CANCEL_BOOKING_SUCCESS',
  CANCEL_BOOKING_FAILURE: 'CANCEL_BOOKING_FAILURE',

  LOAD_DRIVERS_START: 'LOAD_DRIVERS_START',
  LOAD_DRIVERS_SUCCESS: 'LOAD_DRIVERS_SUCCESS',
  LOAD_DRIVERS_FAILURE: 'LOAD_DRIVERS_FAILURE',

  VERIFY_DRIVER_START: 'VERIFY_DRIVER_START',
  VERIFY_DRIVER_SUCCESS: 'VERIFY_DRIVER_SUCCESS',
  VERIFY_DRIVER_FAILURE: 'VERIFY_DRIVER_FAILURE',

  SHOW_CHECKLIST_SUCCESS: 'SHOW_CHECKLIST_SUCCESS',
  SHOW_CHECKLIST_FAILURE: 'SHOW_CHECKLIST_FAILURE',

  POST_CHECKLIST_SUCCESS: 'POST_CHECKLIST_SUCCESS',
  POST_CHECKLIST_FAILURE: 'POST_CHECKLIST_FAILURE',

  GET_BOOKING_COST_SUCCESS: 'GET_COST_SUCCESS',
  GET_BOOKING_COST_FAILURE: 'GET_COST_FAILURE',

  GET_TNC_START: 'GET_TNC_START',
  GET_TNC_SUCCESS: 'GET_TNC_SUCCESS',
  GET_TNC_FAILURE: 'GET_TNC_FAILURE',

  LOAD_EXTENSION_SUCCESS: 'LOAD_EXTENSION_SUCCESS',
  LOAD_EXTENSION_FAILURE: 'LOAD_EXTENSION_FAILURE',

  EXTEND_BOOKING_START: 'EXTEND_BOOKING_START',
  EXTEND_BOOKING_SUCCESS: 'EXTEND_BOOKING_SUCCESS',
  EXTEND_BOOKING_FAILURE: 'EXTEND_BOOKING_FAILURE',

  GET_CONTENT_TYPE_START: 'GET_CONTENT_TYPE_START',
  GET_CONTENT_TYPE_SUCCESS: 'GET_CONTENT_TYPE_SUCCESS',
  GET_CONTENT_TYPE_FAILURE: 'GET_CONTENT_TYPE_FAILURE',

  GET_VEHICLE_IMAGES_START: 'GET_VEHICLE_IMAGES_START',
  GET_VEHICLE_IMAGES_SUCCESS: 'GET_VEHICLE_IMAGES_SUCCESS',
  GET_VEHICLE_IMAGES_FAILURE: 'GET_VEHICLE_IMAGES_FAILURE',

  GET_EXPIRED_LICENSE_SETTING_START: 'GET_EXPIRED_LICENSE_SETTING_START',
  GET_EXPIRED_LICENSE_SETTING_SUCCESS: 'GET_EXPIRED_LICENSE_SETTING_SUCCESS',
  GET_EXPIRED_LICENSE_SETTING_FAILURE: 'GET_EXPIRED_LICENSE_SETTING_FAILURE',
}
