const STRINGS = {
  LABEL_CONFIRM_BOOKING: 'Confirm Booking',
  BOOKING_DETAILS: 'Booking Details',
  TEXT_TERMS_AND_CONDITIONS: 'I accept Terms and Conditions',
  BUTTON_CONFIRM: 'CONFIRM BOOKING',
  BUTTON_MODAL_OKAY: 'Okay',
  BOOKING_SUCCESS_HEADER: 'Booking Created Successfully',
  BOOKING_SUCCESS_MESSAGE:
    'Your booking is under review. Once approved you will be notified on your registered email address.',
  BUTTON_OKAY: 'OK',
  TEXT_BOOKING_ID: 'Booking ID:',
  LABEL_PICK_UP_LOCATION: 'Pick-up Location',
  LABEL_DROP_LOCATION: 'Drop Location',
  LABEL_COST_CENTRE: 'Cost Centre',
  LABEL_START_DATE_TIME: 'Start Date-Time',
  LABEL_END_DATE_TIME: 'End Date-Time',
  LABEL_PURPOSE_OF_TRIP: 'Purpose of Trip',
  LABEL_ENDS_ON: 'Recurring Ends On',
  LABEL_RECURRING: 'Recurring',
  LABEL_ODOMETER: 'Odometer',
  LABEL_YES: 'Yes',
  LABEL_NO: 'No',
  LABEL_NA: 'NA',
  SOMETHING_WENT_WRONG: 'Oops! Something went wrong.',
  BOOKING_UPDATE_MESSAGE: 'Booking Updated Successfully',
  LABEL_EDIT_BOOKING: 'Edit Booking',
  DOLLAR: (cost?: string) => '$' + cost,
  DEFAULT_EXPECTED_COST: 'To be calculated at end of trip',
  ESTIMATED_COST: 'Estimated Cost',
  REVIEW_TERMS: 'Review the Terms',
  VIEW_TERMS: 'Click to view terms and conditions',
}

export default STRINGS
