export const NOTIFICATION_EVENTS = {
  LOAD_NOTIFICATION_LIST_START: 'LOAD_NOTIFICATION_LIST_START',
  LOAD_NOTIFICATION_LIST_SUCCESS: 'LOAD_NOTIFICATION_LIST_SUCCESS',
  LOAD_NOTIFICATION_LIST_FAILURE: 'LOAD_NOTIFICATION_LIST_FAILURE',
}
