export const INCIDENT_EVENTS = {
  LOAD_INCIDENT_LIST_START: 'LOAD_INCIDENT_LIST_START',
  LOAD_INCIDENT_LIST_SUCCESS: 'LOAD_INCIDENT_LIST_SUCCESS',
  LOAD_INCIDENT_LIST_FAILURE: 'LOAD_INCIDENT_LIST_FAILURE',

  LOAD_INCIDENT_FILTERS_START: 'LOAD_INCIDENT_FILTERS_START',
  LOAD_INCIDENT_FILTERS_SUCCESS: 'LOAD_INCIDENT_FILTERS_SUCCESS',
  LOAD_INCIDENT_FILTERS_FAILURE: 'LOAD_INCIDENT_FILTERS_FAILURE',

  LOAD_INCIDENT_START: 'LOAD_INCIDENT_START',
  LOAD_INCIDENT_SUCCESS: 'LOAD_INCIDENT_SUCCESS',
  LOAD_INCIDENT_FAILURE: 'LOAD_INCIDENT_FAILURE',

  POST_NOTE_START: 'POST_NOTE_START',
  POST_NOTE_SUCCESS: 'POST_NOTE_SUCCESS',
  POST_NOTE_FAILURE: 'POST_NOTE_FAILURE',

  LOAD_NOTES_START: 'LOAD_NOTES_START',
  LOAD_NOTES_SUCCESS: 'LOAD_NOTES_SUCCESS',
  LOAD_NOTES_FAILURE: 'LOAD_NOTES_FAILURE',
}
