const STRINGS = {
  BUTTON_BOOK_NOW: 'BOOK NOW!',
  TEXT_NO_BOOKINGS: 'No bookings yet.',
  TEXT_OVERNIGHT: 'Overnight',
  TEXT_RECURRING: 'Recurring',
  DAYS: 'days',
  DAY: 'day',
  ADDRESS: 'Address',
  START_DATE_TIME: 'Start Date-Time',
  END_DATE_TIME: 'End Date-Time',
  BRANCH: 'Branch',
  DRIVER_NAME: 'Driver Name',
  BOOKING_TYPE: 'Booking Type',
  RECURRING: 'Recurring',
  MULTIBOOKING_ID: 'Multibooking ID',
  ACTUAL_COST: 'Actual Cost',
  ESTIMATED_COST: 'Estimated Cost',
  APPROVED: 'Approved',
  INPROGRESS: 'In-Progress',
  COMPLETED: 'Completed',
  DEFAULT_EXPECTED_COST: 'To be calculated at end of trip',
  DOLLAR: (cost?: string) => '$' + cost,
  NA: 'NA',
  COST_CENTRE: 'Cost Centre',
  EDIT_NOT_ALLOWED: 'Sorry! You are not allowed to edit this booking.',
  ARE_YOU_SURE: 'Are you sure?',
  BUTTON_YES: 'Yes',
  BUTTON_NO: 'No',
  DELETE_BOOKING_TITLE: 'Delete Booking',
  SOMETHING_WENT_WRONG: 'Oops! Something went wrong.',
  REGISTRATION_NUMBER: 'Registration No.',
}

export default STRINGS
