const STRINGS = {
  BOOKING_DETAILS: 'Booking Details',
  BUTTON_CHECK_OUT: 'PICK UP',
  BUTTON_CHECK_IN: 'DROP OFF',
  PICK_UP_LOCATION: 'Pick-up Location',
  DROP_LOCATION: 'Drop Location',
  COST_CENTRE: 'Cost Centre',
  START_DATE_TIME: 'Start Date-Time',
  END_DATE_TIME: 'End Date-Time',
  PURPOSE_OF_TRIP: 'Purpose of Trip',
  RECURRING: 'Recurring',
  ODOMETER: 'Odometer',
  OVERNIGHT: 'Overnight',
  NUMBER_OF_DAYS: 'No. of Days',
  ACTUAL_COST: 'Actual Cost',
  ESTIMATED_COST: 'Estimated Cost',
  APPROVED: 'Approved',
  INPROGRESS: 'In-Progress',
  COMPLETED: 'Completed',
  DEFAULT_EXPECTED_COST: 'To be calculated at end of trip',
  DOLLAR: (cost?: string) => '$' + cost,
  CREATED_BY: 'Created By',
  MULTIBOOKING_ID: 'Multibooking ID',
  NA: 'NA',
  YES: 'Yes',
  NO: 'No',
  ERROR_LOADING_BOOKING: 'Oops! Something went wrong.',
  EDIT_NOT_ALLOWED: 'Sorry! You are not allowed to edit this booking.',
  REQUEST_FAILED: 'Sorry! We are not able to process your request at this time',
  CHECK_OUT_SUCCESS: 'Picked up successfully! Now you can start your trip.',
  CHECK_IN_SUCCESS: 'Dropped off successfully!',
  BUTTON_OKAY: 'Okay',
  BUTTON_CANCEL_BOOKING: 'CANCEL BOOKING',
  CANCEL_BOOKING_CONFIRMATION_MESSAGE:
    'Are you sure you want to cancel the booking?',
  BUTTON_YES: 'YES',
  BUTTON_NO: 'NO',
  CANCEL_BOOKING_SUCCESS: 'Booking canceled successfully!',
  BUTTON_EXTEND: 'EXTEND BOOKING',
  EXTEND_SUCCESS: 'Booking extended successfully',
}

export default STRINGS
