const STRINGS = {
  LABEL_PROFILE: 'Profile',
  TITLE_GENERAL: 'General Details',
  TITLE_LICENSE_DETAIL: 'License Details',
  LOGOUT_PROMPT: 'Are you sure you want to logout?',
  BUTTON_YES: 'Yes',
  BUTTON_NO: 'No',
  BUTTON_RETRY: 'Retry',
  UNABLE_TO_LOAD_PROFILE: 'Unable to load profile',
  BADGE_APPROVED: 'Approved',
  BADGE_PENDING: 'Pending',
  BADGE_IN_PROGRESS: 'In Progress',
  EMPLOYEE_NUMBER: 'Employee Number',
  CONTACT_NUMBER: 'Contact Number',
  EMAIL_ID: 'Email ID',
  BRANCH: 'Branch',
  DEPARTMENT: 'Department',
  DEFAULT_COST_CENTRE: 'Default Cost Centre',
  ASSOCIATED_TAGS: 'Associated Tags',
  LICENSE_NUMBER: 'License Number',
  LICENSE_EXPIRY_DATE: 'License Expiry Date',
  LICENSE_CLASS: 'License Class',
  COUNTRY_OF_ISSUE: 'Country Of Issue',
  DAYS_BEFORE_EXPIRY: 'Days Before Expiry',
  REMINDER_RECIPIENTS: 'Reminder recipients',
  LICENSE_STATUS: 'License Status',
  LABEL_CUSTOM_ATTRIBUTES: 'Other Details',
}

export default STRINGS
