export const AUTH_EVENTS = {
  INVALID_INPUT: 'INVALID_INPUT',

  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  RESET_PASSWORD_START: 'RESET_PASSWORD_START',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  LOAD_BRANCHES_START: 'LOAD_BRANCHES_START',
  LOAD_BRANCHES_SUCCESS: 'LOAD_BRANCHES_SUCCESS',
  LOAD_BRANCHES_FAILURE: 'LOAD_BRANCHES_FAILURE',

  LOAD_PROFILE_START: 'LOAD_PROFILE_START',
  LOAD_PROFILE_SUCCESS: 'LOAD_PROFILE_SUCCESS',
  LOAD_PROFILE_FAILURE: 'LOAD_PROFILE_FAILURE',

  LOAD_REPORT_START: 'LOAD_REPORT_START',
  LOAD_REPORT_SUCCESS: 'LOAD_REPORT_SUCCESS',
  LOAD_REPORT_FAILURE: 'LOAD_REPORT_FAILURE',

  UPDATE_PROFILE_START: 'UPDATE_PROFILE_START',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',

  LOAD_DISPLAY_PRIORITY_START: 'LOAD_DISPLAY_PRIORITY_START',
  LOAD_DISPLAY_PRIORITY_SUCCESS: 'LOAD_DISPLAY_PRIORITY_SUCCESS',
  LOAD_DISPLAY_PRIORITY_FAILURE: 'LOAD_DISPLAY_PRIORITY_FAILURE',

  CHANGE_PASSWORD_START: 'CHANGE_PASSWORD_START',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  REQUEST_OTP_START: 'REQUEST_OTP_START',
  REQUEST_OTP_SUCCESS: 'REQUEST_OTP_SUCCESS',
  REQUEST_OTP_FAILURE: 'REQUEST_OTP_FAILURE',

  VERIFY_EMAIL_START: 'VERIFY_EMAIL_START',
  VERIFY_EMAIL_SUCCESS: 'VERIFY_EMAIL_SUCCESS',
  VERIFY_EMAIL_FAILURE: 'VERIFY_EMAIL_FAILURE',

  LOAD_PROFILE_DETAILS_START: 'LOAD_PROFILE_DETAILS_START',
  LOAD_PROFILE_DETAILS_SUCCESS: 'LOAD_PROFILE_DETAILS_SUCCESS',
  LOAD_PROFILE_DETAILS_FAILURE: 'LOAD_PROFILE_DETAILS_FAILURE',

  LOAD_HOLIDAY_SETTINGS_START: 'LOAD_HOLIDAY_SETTINGS_START',
  LOAD_HOLIDAY_SETTINGS_SUCCESS: 'LOAD_HOLIDAY_SETTINGS_SUCCESS',
  LOAD_HOLIDAY_SETTINGS_FAILURE: 'LOAD_HOLIDAY_SETTINGS_FAILURE',

  LOAD_HOLIDAY_LIST_START: 'LOAD_HOLIDAY_LIST_START',
  LOAD_HOLIDAY_LIST_SUCCESS: 'LOAD_HOLIDAY_LIST_SUCCESS',
  LOAD_HOLIDAY_LIST_FAILURE: 'LOAD_HOLIDAY_LIST_FAILURE',

  LOAD_REMEMBER_ME_STATE_SUCCESS: 'LOAD_REMEMBER_ME_STATE_SUCCESS',

  SSO_START: 'SSO_START',
  SSO_SUCCESS: 'SSO_SUCCESS',
  SSO_FAILURE: 'SSO_FAILURE',
}
